//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package suspicious/unexpected

type bland struct {
	Sample string
}

var MpaaRating = &struct {
	G    string
	Pg   string
	Pg13 string
	R    string
	Nc17 string
}{
	G:    "G",
	Pg:   "PG",
	Pg13: "PG-13",
	R:    "R",
	Nc17: "NC-17",
}
